#ifndef CLIENT_UDPSERVER_MSG_H
#define CLIENT_UDPSERVER_MSG_H
enum {//request&response
	MULTI_FORWARD_MSG =0x50,// msg<0x50 => require forward
	LOGIN_MSG = 0x51,
	LOGOUT_MSG,
	UPDATE_FORWARD_TABLE_MSG,
	ACK_LOGIN,
	ACK_LOGOUT,
	ACK_UPDATE_FORWARDTABLE,
	GET_P2P_ADDR_MSG=0x57,
	ACK_P2P_ADDR=0x58,
	SINGLE_FORWARD_MSG,
	SERVER_TEST_BEGIN =0x70,
	ACK_SERVER_TEST_BEGIN,
	SERVER_TEST_END,
	ACK_SERVER_TEST_END,
	PUNCH_HOLE_MSG1,
	PUNCH_HOLE_MSG2
};
#endif  // CLIENT_UDPSERVER_H