all:
	cd $(WORK_ROOT)/src/simple_uv && make clean && make
	cd $(WORK_ROOT)/src/relay_server_sdk && make clean && make
	cd $(WORK_ROOT)/src/relay_server_main && make clean && make
	cd $(WORK_ROOT)/src/relay_server_master && make clean && make
	

clean:
	cd $(WORK_ROOT)/src/simple_uv && make clean 
	cd $(WORK_ROOT)/src/relay_server_sdk && make clean
	cd $(WORK_ROOT)/src/relay_server_main && make clean
	cd $(WORK_ROOT)/src/relay_server_master && make clean
